all:
	javac -g *.java

run: all
	java Bank

testAdmin: all
	java Admin

testCustomer: all
	java Customer

testChecking: all
	java CheckingAccount

testSavings: all
	java SavingsAccount

clean:
	rm *.class
